version: '3.1'

services:
  server:
    image: node:12.10.0-alpine
    container_name: log_api_server
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/app"
      - "/usr/app/node_modules"
    links:
      - database
    command: sh -c "cd /usr/app/ && npm i && npm run dev"

  database:
    image: postgres
    container_name: log_api_db
    ports:
      - "5432:5432"
    volumes:
      - /usr/postgres/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: log_api
      PGDATA: /usr/postgres/data/
